controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: false

    armgroup_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

armgroup_controller:
  ros__parameters:
    joints:
      - BaseRotate_0
      - UpperArmRotate_0
      - ForeArmRotate_0
      - WristRotate_0
      - PaddleRotate_0
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    use_sim_time: false

joint_state_broadcaster:
  ros__parameters:
    joints:
      - BaseRotate_0
      - UpperArmRotate_0
      - ForeArmRotate_0
      - WristRotate_0
      - PaddleRotate_0
    use_sim_time: false