/**:
  ros__parameters:
    camera_baseline: 1.5

    left_camera:
      x: -0.75
      y: 0.0
      z: 1.0
      roll: 0.0
      pitch: -0.785
      yaw: 0.0

    right_camera:
      x: 0.75
      y: 0.0
      z: 1.0
      roll: 0.0
      pitch: -0.785
      yaw: 0.0

    robot_base:
      x: 0.0
      y: -1.0
      z: 0.0
      roll: 0.0
      pitch: 0.0
      yaw: 0.0