# Default initial positions for mainarmass's ros2_control fake system
# Values must be within URDF joint limits:
#   UpperArmRotate_0: [-0.2617, 1.3963]
#   ForeArmRotate_0:  [-4.1888, 0.5236]
#   WristRotate_0:    [-2.967,  2.50]

initial_positions:
  BaseRotate_0: 0.0
  UpperArmRotate_0: 0.0
  ForeArmRotate_0: -2.59
  WristRotate_0: 2.33
  PaddleRotate_0: 0.0
